services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/**/Entity/*'
            - '../src/**/ValueObject/*'
            - '../src/**/DTO/*'
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    _instanceof:
        App\Shared\Application\Query\QueryHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'query.bus' }
        App\Shared\Application\Command\CommandHandlerInterface:
            tags:
                - { name: 'internal.command_handler', bus: 'command.bus'}
  ### Buses
    App\Shared\Application\Command\CommandBus:
      class: App\Shared\Application\Command\CommandBus
      arguments: [ !tagged internal.command_handler ]
  ### Listeners
    App\User\Application\Event\Listener\UserCreatedListener:
        tags:
            - { name: 'kernel.event_listener', event: 'user.created' }
    App\User\Application\Event\Listener\UserDeletedListener:
        tags:
            - { name: 'kernel.event_listener', event: 'user.deleted' }