services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/**/Entity/*'
            - '../src/**/ValueObject/*'
            - '../src/**/DTO/*'
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    _instanceof:
        App\Application\Shared\Query\QueryHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'query.bus' }
        App\Application\Shared\Command\CommandHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'command.bus'}
    app.command_bus:
        class: App\Application\Shared\Command\CommandBus
        public: false
        arguments: [ [ ] ]
        tags:
            - { name: command.bus, default: true }